import Head from 'next/head';
import styles from '../styles/index.module.css';
import Image from 'next/image';
import logo from '../public/images/test.png';
import make_your_choice from '../public/images/make_your_choice.png';
import left_image from '../public/images/left_image.png';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {
    const logo_group_class_name = `${styles.header_logo_group} link`;
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <div className={styles.header_logo_group}>
                    <Link href="/" className={logo_group_class_name}>
                        <Image
                            src={logo}
                            alt="Picture of the author"
                            width={40}
                            height={40}
                        />
                        <p className={styles.header__text}>jevote</p>
                    </Link>
                </div>

                <nav className={styles.header__nav}>
                    <ul>
                        <li>
                            <Link
                                href="/"
                                className={
                                    router.pathname === '/'
                                        ? 'link active'
                                        : 'link'
                                }
                            >
                                A propos
                            </Link>
                        </li>
                        <li>
                            <Link
                                href="/tarifs"
                                className={
                                    router.pathname === '/tarifs'
                                        ? 'link active'
                                        : 'link'
                                }
                            >
                                Tarifs
                            </Link>
                        </li>
                        <li>
                            <Link
                                href="/testimonies"
                                className={
                                    router.pathname === '/testimonies'
                                        ? 'link active'
                                        : 'link'
                                }
                            >
                                Témoignages
                            </Link>
                        </li>
                        <li>
                            <Link
                                href="/contact"
                                className={
                                    router.pathname === '/contact'
                                        ? 'link active'
                                        : 'link'
                                }
                            >
                                Contact
                            </Link>
                        </li>
                    </ul>
                    <Link href="/login">
                        <button className="button_primary">Se connecter</button>
                    </Link>
                </nav>
            </header>

            <main className={styles.main}>
                <div>
                    <Image src={left_image} alt="Fais ton choix" width={147} />
                </div>

                <section className={styles.section_text}>
                    <h1>Créez votre vote en ligne maintenant</h1>
                    <ul>
                        <li>Gestion simple des élections</li>
                        <li>Sécurité et protection des données maximales</li>
                        <li>
                            Des résultats d'élections corrects en un clic de
                            souris
                        </li>
                    </ul>
                    <Link href="/">
                        <button className="button_primary">Commencer</button>
                    </Link>
                </section>

                <section>
                    <Image
                        src={make_your_choice}
                        alt="Fais ton choix"
                        width={434}
                    />
                </section>
            </main>
        </>
    );
}
