import Head from 'next/head';
import styles from '../styles/index.module.css';
import Image from 'next/image';
import logo from '../public/images/test.png';
import make_your_choice from '../public/images/make_your_choice.png';
import left_image from '../public/images/left_image.png';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <div className={styles.header_logo_group}>
                    <Image
                        src={logo}
                        alt="Picture of the author"
                        width={40}
                        height={40}
                    />
                    <p className={styles.header__text}>jevote</p>
                </div>

                <nav className={styles.header__nav}>
                    <ul>
                        <li>
                            <Link
                                href="/"
                                className={
                                    router.pathname === '/'
                                        ? 'link active'
                                        : 'link'
                                }
                            >
                                A propos
                            </Link>
                        </li>
                        <li>
                            <Link href="/tarifs" className="link">
                                Tarifs
                            </Link>
                        </li>
                        <li>
                            <Link href="/testimony" className="link">
                                Témoignages
                            </Link>
                        </li>
                        <li>
                            <Link href="/contact" className="link">
                                Contact
                            </Link>
                        </li>
                    </ul>

                    <button className="button_primary">Se connecter</button>
                </nav>
            </header>
            <main className={styles.main}>
                <div>
                    <Image src={left_image} alt="Fais ton choix" width={147} />
                </div>

                <section>
                    <h1>Créez votre vote en ligne maintenant</h1>
                    <ul>
                        <li>Gestion simple des élections</li>
                        <li>Sécurité et protection des données maximales</li>
                        <li>
                            Des résultats d'élections corrects en un clic de
                            souris
                        </li>
                    </ul>
                    <button>Commencer</button>
                </section>
                <section>
                    <Image
                        src={make_your_choice}
                        alt="Fais ton choix"
                        width={434}
                    />
                </section>
            </main>
        </>
    );
}
