import Head from 'next/head';
import styles from '../styles/index.module.css';
import Image from 'next/image';
import make_your_choice from '../public/images/make_your_choice.png';
import left_image from '../public/images/left_image.png';
import Link from 'next/link';
import { Header } from '../components';
import { useEffect } from 'react';
import { route_for_register } from '../public/routes';

export default function Home() {

    // const [test, setTest] =useState(process.env.NEXT_PUBLIC_API)
    
    useEffect(()=>{
        // eslint-disable-next-line no-console
        console.log('ROUTE URL',route_for_register)

    }, [])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <div>
                    <Image src={left_image} alt="Fais ton choix" width={147} />
                </div>

                <section className={styles.section_text}>
                    <h1>Créez votre vote en ligne maintenant</h1>
                    <ul>
                        <li>Gestion simple des élections</li>
                        <li>Sécurité et protection des données maximales</li>
                        <li>
                            Des résultats d'élections corrects en un clic de
                            souris
                        </li>
                    </ul>
                    <Link href="/login">
                        <button className="button_primary">Commencer</button>
                    </Link>
                </section>

                <section>
                    <Image
                        src={make_your_choice}
                        alt="Fais ton choix"
                        width={434}
                    />
                </section>
            </main>
        </>
    );
}
